### PR TITLE
Fixes #51 - map request to docker parameter and add test to validate.

### LINKED ISSUE #51: forcePull in TaskDef not used when creating tasks
Hi.

I am not a Scala programmer, so I might be wrong. It seems that the forcePull paramter, although defined in the TaskDef is never passed to Mesos.

The `forcePull` parameter is defined here: https://github.com/adobe-apiplatform/mesos-actor/blob/master/src/main/scala/com/adobe/api/platform/runtime/mesos/MesosClient.scala#L108 but it is not being used here: https://github.com/adobe-apiplatform/mesos-actor/blob/master/src/main/scala/com/adobe/api/platform/runtime/mesos/TaskBuilder.scala#L63

### PR DESCRIPTION
**Pull request by mcdan**

### CODE REVIEW

**Review by ddragosd — APPROVED** [review]
LGTM

**Comment by alvarolopez** [comment]
Hi there.

Any ETA on when this can be merged and released?

**Comment by alvarolopez** [comment]
Hi @ddragosd 

This is one feature that we are eager to use. Are there any reasons not to implement it?

**Review by ddragosd — APPROVED** [review]

**Comment by ddragosd** [comment]
@mcdan do you see any issues with merging this ? It LGTM !

@alvarolopez thanks for pinging again. I'll try to merge it ASAP. Thanks for your patience.

**Pull request merged**
